### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by chy89310** [maokebing/MISImagePicker#1]
我見你的插件剛好適合我的項目，但由於有別的插件的依賴，似乎直接添加到項目中存在一定困難，請問有沒有計劃放上cocoapod上呢？

**Comment by maokebing** [comment]
暂时没有计划放到上面。不过我可以解一下依赖，主要就是依赖了Masonry, 你可以稍稍修改一下，import Masony的地方。我会最近更新提交一次，尽量达到0依赖的。

**Comment by maokebing** [comment]
我把宏定义都去掉了。分类也没有了。仅剩下Masonry了和MBProgressHUD了。很容易适配你的项目了。见tag 1.1

**Comment by chy89310** [comment]
非常感謝！
